# numpy
- n 차원 배열 (ndarray)을 사용하기 위한 라이브러리
- 기타 숫자를 다루는 함수 제공

In [17]:
import numpy as np

In [69]:
x = [1, 2, 10]
print(x * 3)

[1, 2, 10, 1, 2, 10, 1, 2, 10]


## 리스트 <--> 배열
### 벡터화: 배열에 상수를 곱하거나 더할 수 있다


In [3]:
# [ 리스트, 인덱싱
# : if, for, def
# ( 함수호출, 튜플
# { 딕셔너리, DB
import numpy as np
x = np.array([1,2,3]);x

array([1, 2, 3])

In [5]:
x *3

array([3, 6, 9])

In [19]:
arr = np.array(x)
print(arr * 3)

[ 3  6 30]


In [20]:
arr + 1

array([101, 102, 110])

In [21]:
# 배열의 각 항목의 타입을 알아보려면 dtype 속성값을 보면 된다
arr.dtype

dtype('int64')

In [22]:
# 배열의 구조를 보려면 shape 속성을 보면 된다
arr.shape

(3,)

In [56]:
type(arr)

numpy.ndarray

In [67]:
y = arr.tolist()
y

[1, 2, 10]

In [68]:
type(y)

list

## arange

In [23]:
# 레인지 형태로 배열을 만드는 법
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [24]:
# 데이터의 타입을 변경하려면 astype을 사용한다
x.astype(np.float32)

array([0., 1., 2., 3., 4.], dtype=float32)

In [37]:
# 0~11 값을 얻고 이를 4x3 배열로 재구성한다
data = np.arange(12).reshape(4,3)
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
# 5 보다 큰 값을 모두 5로 교체하는 방법
data[data > 5] = 5
data

array([[0, 1, 2],
       [3, 4, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [39]:
data[0]

array([0, 1, 2])

In [43]:
data[1]

array([3, 4, 5])

In [44]:
data[[1,0]]

array([[3, 4, 5],
       [0, 1, 2]])

In [45]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [71]:
# 행과 열 일부를 얻기
data[:,[0,1]]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]])

In [47]:
# 트랜스포즈는 행과 열의 위치를 바꾸는 것이다
data.T

array([[0, 3, 5, 5],
       [1, 4, 5, 5],
       [2, 5, 5, 5]])

In [49]:
data = np.arange(24).reshape(6,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [50]:
# 각 행에 대해서 평균을 구한다 axis=1이면 행을 지칭한다
data.mean(axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5, 21.5])

In [51]:
# axis를 생략해도 된다
data.mean(1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5, 21.5])

In [55]:
data.mean(0)

array([10., 11., 12., 13.])

In [54]:
data.mean()

11.5